export const SERVER_URL = "http://localhost:8080"
export const MAIN_PAGE = "/"
export const LOGIN_PAGE = "/login"
export const SIGNUP_PAGE = "/signup"
export const USER_PAGE = "/profile"
export const CHECKOUT_PAGE = "/checkout"